[package]
name = "samegame-sfc-small"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.83"
arrayvec = "0.7.4"
itertools = "0.12.1"
rand = "0.8.5"

[dev-dependencies]
clap = { version = "4.5.4", features = ["derive"] }
indoc = "2.0.5"
parse_int = "0.6.0"
